//
//  HistoryManager.swift
//  NeuroLearn
//
//  Created by Dev Jr. 15 on 20/04/26.
//

//
//  HistoryManager.swift
//  NeuroLearn
//

import Foundation
import SwiftUI

@Observable
class HistoryManager {
    static let shared = HistoryManager()
    
    var savedPlans: [LearningPlan] = []
    
    private let saveKey = "SavedLearningPlans"
    
    init() {
        loadPlans()
    }
    
    // Save a new plan generated by the AI
    func savePlan(_ plan: LearningPlan) {
        // Prevent duplicate topics from cluttering the history
        if !savedPlans.contains(where: { $0.topic == plan.topic }) {
            savedPlans.insert(plan, at: 0) // Add newest to the top
            persistData()
        }
    }
    
    // Load plans from device storage
    private func loadPlans() {
        if let data = UserDefaults.standard.data(forKey: saveKey) {
            if let decoded = try? JSONDecoder().decode([LearningPlan].self, from: data) {
                savedPlans = decoded
                return
            }
        }
        savedPlans = []
    }
    
    // Encode and write to device storage
    private func persistData() {
        if let encoded = try? JSONEncoder().encode(savedPlans) {
            UserDefaults.standard.set(encoded, forKey: saveKey)
        }
    }
}
